project_name: gorgany
before:
  hooks:
    - go mod tidy
builds:
  - binary: 'gorgany'
    main: ./cmd/gorgany
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/andrii-zakurenyi/gorgany/pkg/version.GitTag={{ .Summary }}
      - -X github.com/andrii-zakurenyi/gorgany/pkg/version.GitCommit={{ .FullCommit }}
    targets:
      - windows_386
      - windows_amd64
      - linux_386
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
archives:
  - format: binary
    # Name template is: 'gorgany-{{ .Os }}-{{ .Arch }}',
    # but we replace:
    #     - "windows" with "win"
    #     - "386" with "x86"
    #     - "amd64" with "x64"
    # Example: "gorgany-windows-amd64.exe" -> "gorgany-win-x64.exe"
    name_template: 'gorgany-{{ replace .Os "windows" "win" }}-{{ if eq .Arch "386" }}x86{{ else if eq .Arch "amd64" }}x64{{ else }}{{ .Arch }}{{end}}'
release:
  name_template: "Gorgany CLI {{.Version}}"
  github:
    owner: andrii-zakurenyi
    name: gorgany
nfpms:
  - license: "Apache-2.0"
    maintainer: Andrii.Zakurenyi@c.delinea.com
    homepage: https://github.com/andrii-zakurenyi/gorgany
    bindir: /usr/bin
    description: Gorgany | Testing Things
    formats:
      - deb
      - rpm
brews:
  - tap:
      owner: andrii-zakurenyi
      name: homebrew-gorgany
      branch: main
    homepage: https://github.com/andrii-zakurenyi/gorgany
    folder: Formula
    description: Gorgany | Testing Things
    license: "Apache-2.0"